/*
 * Simple multiply service demo
 */

/*
 * Generated by erpcgen 1.14.0 on Fri Oct 17 16:27:45 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_multiply_demo_server_hpp_)
#define _multiply_demo_server_hpp_

#include "multiply_demo_interface.hpp"

#include "erpc_server.hpp"
#include "erpc_codec.hpp"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


namespace erpcShim
{

/*!
 * @brief Service subclass for MultiplyService.
 */
class MultiplyService_service : public erpc::Service
{
public:
    MultiplyService_service(MultiplyService_interface *_MultiplyService_interface);

    virtual ~MultiplyService_service();

    /*! @brief return service interface handler. */
    MultiplyService_interface* getHandler(void);

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport);

private:
    MultiplyService_interface *m_handler;
    /*! @brief Server shim for multiply of MultiplyService interface. */
    erpc_status_t multiply_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);
};

} // erpcShim


#endif // _multiply_demo_server_hpp_
