/*
 * Simple multiply service demo
 */

/*
 * Generated by erpcgen 1.14.0 on Fri Oct 17 16:27:45 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_multiply_demo_common_h_)
#define _multiply_demo_common_h_


#if defined(__cplusplus)
extern "C"
{
#endif
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "erpc_version.h"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_TYPE_DEFINITIONS_MULTIPLY_DEMO)
#define ERPC_TYPE_DEFINITIONS_MULTIPLY_DEMO

#endif // ERPC_TYPE_DEFINITIONS_MULTIPLY_DEMO

#if defined(__cplusplus)
}
#endif

#endif // _multiply_demo_common_h_
