/*
 * Calculator service demonstrating remote procedure calls
 */

/*
 * Generated by erpcgen 1.14.0 on Thu Oct 30 12:45:04 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_calculator_client_h_)
#define _c_calculator_client_h_

#include "calculator_common.h"
#include "erpc_client_manager.h"

#if defined(__cplusplus)
extern "C"
{
#endif

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief Calculator identifiers */
enum _Calculator_ids
{
    kCalculator_service_id = 1,
    kCalculator_add_id = 1,
    kCalculator_subtract_id = 2,
    kCalculator_multiply_id = 3,
    kCalculator_divide_id = 4,
};

//! @name Calculator
//@{
int32_t add(int32_t a, int32_t b);

int32_t subtract(int32_t a, int32_t b);

int32_t multiply(int32_t a, int32_t b);

float divide(int32_t a, int32_t b);
//@}

#endif // ERPC_FUNCTIONS_DEFINITIONS

void initCalculator_client(erpc_client_t client);

void deinitCalculator_client(void);

#if defined(__cplusplus)
}
#endif

#endif // _c_calculator_client_h_
