/*
 * Calculator service demonstrating remote procedure calls
 */

/*
 * Generated by erpcgen 1.14.0 on Thu Oct 30 12:45:04 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_calculator_client_hpp_)
#define _calculator_client_hpp_

#include "calculator_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class Calculator_client: public Calculator_interface
{
    public:
        Calculator_client(erpc::ClientManager *manager);

        virtual ~Calculator_client();

        virtual int32_t add(int32_t a, int32_t b);

        virtual int32_t subtract(int32_t a, int32_t b);

        virtual int32_t multiply(int32_t a, int32_t b);

        virtual float divide(int32_t a, int32_t b);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _calculator_client_hpp_
