/*
 * Calculator service demonstrating remote procedure calls
 */

/*
 * Generated by erpcgen 1.14.0 on Thu Oct 30 12:45:04 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_calculator_common_h_)
#define _calculator_common_h_


#if defined(__cplusplus)
extern "C"
{
#endif
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "erpc_version.h"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_TYPE_DEFINITIONS_CALCULATOR)
#define ERPC_TYPE_DEFINITIONS_CALCULATOR

#endif // ERPC_TYPE_DEFINITIONS_CALCULATOR

#if defined(__cplusplus)
}
#endif

#endif // _calculator_common_h_
