/*
 * Calculator service demonstrating remote procedure calls
 */

/*
 * Generated by erpcgen 1.14.0 on Thu Oct 30 12:45:04 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_calculator_common_hpp_)
#define _calculator_common_hpp_


#include <cstddef>
#include <cstdint>

#include "erpc_version.h"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_TYPE_DEFINITIONS_CALCULATOR)
#define ERPC_TYPE_DEFINITIONS_CALCULATOR

#endif // ERPC_TYPE_DEFINITIONS_CALCULATOR


#endif // _calculator_common_hpp_
