MODULE = erpc_nrf_demo_shared

SRCS += riot_uart_transport.cpp
SRCS += calculator_client.cpp
SRCS += calculator_server.cpp
SRCS += calculator_interface.cpp
SRCS += c_calculator_client.cpp
SRCS += c_calculator_server.cpp

include $(RIOTBASE)/Makefile.base
