/*
 * Enhanced RPC Demo Service for Bachelor Thesis
 * "Implementation and Evaluation of a Lightweight RPC System 
 * for Resource-Constrained Devices using RIOT OS"
 * 
 * Demonstrates various data types: integers, enums, strings, arrays, structs
 */

/*
 * Generated by erpcgen 1.14.0 on Mon Dec  8 10:24:32 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_demo_service_interface_hpp_)
#define _demo_service_interface_hpp_

#include "demo_service_common.hpp"

namespace erpcShim
{


// Abstract base class for DemoService
class DemoService_interface
{
    public:
        static const uint8_t m_serviceId = 1;
        static const uint8_t m_calculateId = 1;
        static const uint8_t m_processStringId = 2;
        static const uint8_t m_sortArrayId = 3;

        virtual ~DemoService_interface(void);

        virtual CalcResult * calculate(int32_t a, int32_t b, ArithmeticOp operation) = 0;

        virtual StringResult * processString(const char * input, StringOp operation) = 0;

        virtual IntArray * sortArray(const IntArray * input_array) = 0;
private:
};
} // erpcShim


#endif // _demo_service_interface_hpp_
