/*
 * Enhanced RPC Demo Service for Bachelor Thesis
 * "Implementation and Evaluation of a Lightweight RPC System 
 * for Resource-Constrained Devices using RIOT OS"
 * 
 * Demonstrates various data types: integers, enums, strings, arrays, structs
 */

/*
 * Generated by erpcgen 1.14.0 on Mon Dec  8 10:24:32 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_demo_service_common_h_)
#define _demo_service_common_h_


#if defined(__cplusplus)
extern "C"
{
#endif
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "erpc_version.h"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_TYPE_DEFINITIONS_DEMO_SERVICE)
#define ERPC_TYPE_DEFINITIONS_DEMO_SERVICE

// Enumerators data types declarations
typedef enum ArithmeticOp
{
    OP_ADD = 0,
    OP_SUBTRACT = 1,
    OP_MULTIPLY = 2,
    OP_DIVIDE = 3
} ArithmeticOp;

typedef enum StringOp
{
    STR_REMOVE_SPACES = 0,
    STR_TO_UPPER = 1,
    STR_TO_LOWER = 2,
    STR_COUNT_DIGITS = 3
} StringOp;

// Aliases data types declarations
typedef struct list_int32_1_t list_int32_1_t;
typedef struct CalcResult CalcResult;
typedef struct StringResult StringResult;
typedef struct IntArray IntArray;

// Structures/unions data types declarations
struct list_int32_1_t
{
    int32_t * elements;
    uint32_t elementsCount;
};

struct CalcResult
{
    int32_t result;
    int32_t status;
};

struct StringResult
{
    char * output_str;
    int32_t count;
    int32_t status;
};

struct IntArray
{
    int32_t length;
    list_int32_1_t data;
};


#endif // ERPC_TYPE_DEFINITIONS_DEMO_SERVICE

#if defined(__cplusplus)
}
#endif

#endif // _demo_service_common_h_
