/*
 * Enhanced RPC Demo Service for Bachelor Thesis
 * "Implementation and Evaluation of a Lightweight RPC System 
 * for Resource-Constrained Devices using RIOT OS"
 * 
 * Demonstrates various data types: integers, enums, strings, arrays, structs
 */

/*
 * Generated by erpcgen 1.14.0 on Mon Dec  8 10:24:32 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_demo_service_client_hpp_)
#define _demo_service_client_hpp_

#include "demo_service_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class DemoService_client: public DemoService_interface
{
    public:
        DemoService_client(erpc::ClientManager *manager);

        virtual ~DemoService_client();

        virtual CalcResult * calculate(int32_t a, int32_t b, ArithmeticOp operation);

        virtual StringResult * processString(const char * input, StringOp operation);

        virtual IntArray * sortArray(const IntArray * input_array);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _demo_service_client_hpp_
