MODULE = erpc_menu_nrf_shared

SRCXXEXT = cpp
SRCXX += riot_uart_transport.cpp
SRCXX += demo_service_interface.cpp
SRCXX += demo_service_server.cpp
SRCXX += demo_service_client.cpp
SRCXX += c_demo_service_client.cpp
SRCXX += c_demo_service_server.cpp

include $(RIOTBASE)/Makefile.base
