/*
 * Enhanced RPC Demo Service for Bachelor Thesis
 * "Implementation and Evaluation of a Lightweight RPC System 
 * for Resource-Constrained Devices using RIOT OS"
 * 
 * Demonstrates various data types: integers, enums, strings, arrays, structs
 */

/*
 * Generated by erpcgen 1.14.0 on Mon Dec  8 10:24:32 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include <new>
#include "c_demo_service_server.h"
#include "demo_service_server.hpp"
#include "erpc_manually_constructed.hpp"

using namespace erpc;
using namespace std;
using namespace erpcShim;


class DemoService_server: public DemoService_interface
{
    public:
        virtual ~DemoService_server() {};


        CalcResult * calculate(int32_t a, int32_t b, ArithmeticOp operation)
        {
            CalcResult * result = NULL;
            result = ::calculate(a, b, operation);

            return result;
        }

        StringResult * processString(const char * input, StringOp operation)
        {
            StringResult * result = NULL;
            result = ::processString(input, operation);

            return result;
        }

        IntArray * sortArray(const IntArray * input_array)
        {
            IntArray * result = NULL;
            result = ::sortArray(input_array);

            return result;
        }
};

ERPC_MANUALLY_CONSTRUCTED_STATIC(DemoService_service, s_DemoService_service);
ERPC_MANUALLY_CONSTRUCTED_STATIC(DemoService_server, s_DemoService_server);

erpc_service_t create_DemoService_service(void)
{
    erpc_service_t service;

#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    service = new (nothrow) DemoService_service(new (nothrow)DemoService_server());
#else
    if (s_DemoService_service.isUsed())
    {
        service = NULL;
    }
    else
    {
        s_DemoService_server.construct();
        s_DemoService_service.construct(s_DemoService_server.get());
        service = s_DemoService_service.get();
    }
#endif

    return service;
}

void destroy_DemoService_service(erpc_service_t service)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    if (service)
    {
        delete (DemoService_server *)(((DemoService_service *)service)->getHandler());
        delete (DemoService_service *)service;
    }
#else
    (void)service;
    erpc_assert(service == s_DemoService_service.get());
    s_DemoService_service.destroy();
    s_DemoService_server.destroy();
#endif
}

