/*
 * Enhanced RPC Demo Service for Bachelor Thesis
 * "Implementation and Evaluation of a Lightweight RPC System 
 * for Resource-Constrained Devices using RIOT OS"
 * 
 * Demonstrates various data types: integers, enums, strings, arrays, structs
 */

/*
 * Generated by erpcgen 1.14.0 on Mon Dec  8 10:24:32 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "c_demo_service_client.h"
#include "demo_service_client.hpp"
#include "erpc_manually_constructed.hpp"

using namespace erpc;
using namespace std;
using namespace erpcShim;


#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
DemoService_client *s_DemoService_client = nullptr;
#else
ERPC_MANUALLY_CONSTRUCTED_STATIC(DemoService_client, s_DemoService_client);
#endif

CalcResult * calculate(int32_t a, int32_t b, ArithmeticOp operation)
{
    CalcResult * result = NULL;
    result = s_DemoService_client->calculate(a, b, operation);

    return result;
}

StringResult * processString(const char * input, StringOp operation)
{
    StringResult * result = NULL;
    result = s_DemoService_client->processString(input, operation);

    return result;
}

IntArray * sortArray(const IntArray * input_array)
{
    IntArray * result = NULL;
    result = s_DemoService_client->sortArray(input_array);

    return result;
}

void initDemoService_client(erpc_client_t client)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    erpc_assert(s_DemoService_client == nullptr);
    s_DemoService_client = new DemoService_client(reinterpret_cast<ClientManager *>(client));
#else
    erpc_assert(!s_DemoService_client.isUsed());
    s_DemoService_client.construct(reinterpret_cast<ClientManager *>(client));
#endif
}

void deinitDemoService_client(void)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    if (s_DemoService_client != nullptr)
    {
        delete s_DemoService_client;
        s_DemoService_client = nullptr;
    }
#else
    s_DemoService_client.destroy();
#endif
}
