/*
 * Enhanced RPC Demo Service for Bachelor Thesis
 * "Implementation and Evaluation of a Lightweight RPC System 
 * for Resource-Constrained Devices using RIOT OS"
 * 
 * Demonstrates various data types: integers, enums, strings, arrays, structs
 */

/*
 * Generated by erpcgen 1.14.0 on Mon Dec  8 10:24:32 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_demo_service_client_h_)
#define _c_demo_service_client_h_

#include "demo_service_common.h"
#include "erpc_client_manager.h"

#if defined(__cplusplus)
extern "C"
{
#endif

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief DemoService identifiers */
enum _DemoService_ids
{
    kDemoService_service_id = 1,
    kDemoService_calculate_id = 1,
    kDemoService_processString_id = 2,
    kDemoService_sortArray_id = 3,
};

//! @name DemoService
//@{
CalcResult * calculate(int32_t a, int32_t b, ArithmeticOp operation);

StringResult * processString(const char * input, StringOp operation);

IntArray * sortArray(const IntArray * input_array);
//@}

#endif // ERPC_FUNCTIONS_DEFINITIONS

void initDemoService_client(erpc_client_t client);

void deinitDemoService_client(void);

#if defined(__cplusplus)
}
#endif

#endif // _c_demo_service_client_h_
