/*
 * Enhanced RPC Demo Service for Bachelor Thesis
 * "Implementation and Evaluation of a Lightweight RPC System 
 * for Resource-Constrained Devices using RIOT OS"
 * 
 * Demonstrates various data types: integers, enums, strings, arrays, structs
 */

/*
 * Generated by erpcgen 1.14.0 on Mon Dec  8 10:24:32 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
#include "erpc_port.h"
#endif
#include "erpc_codec.hpp"
#include "demo_service_client.hpp"
#include "erpc_manually_constructed.hpp"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

using namespace erpc;
using namespace std;
using namespace erpcShim;

//! @brief Function to write struct IntArray
static void write_IntArray_struct(erpc::Codec * codec, const IntArray * data);

//! @brief Function to write struct list_int32_1_t
static void write_list_int32_1_t_struct(erpc::Codec * codec, const list_int32_1_t * data);


// Write struct IntArray function implementation
static void write_IntArray_struct(erpc::Codec * codec, const IntArray * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->write(data->length);

    write_list_int32_1_t_struct(codec, &(data->data));
}

// Write struct list_int32_1_t function implementation
static void write_list_int32_1_t_struct(erpc::Codec * codec, const list_int32_1_t * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->startWriteList(data->elementsCount);
    for (uint32_t listCount = 0U; listCount < data->elementsCount; ++listCount)
    {
        codec->write(data->elements[listCount]);
    }
}


//! @brief Function to read struct CalcResult
static void read_CalcResult_struct(erpc::Codec * codec, CalcResult * data);

//! @brief Function to read struct StringResult
static void read_StringResult_struct(erpc::Codec * codec, StringResult * data);

//! @brief Function to read struct IntArray
static void read_IntArray_struct(erpc::Codec * codec, IntArray * data);

//! @brief Function to read struct list_int32_1_t
static void read_list_int32_1_t_struct(erpc::Codec * codec, list_int32_1_t * data);


// Read struct CalcResult function implementation
static void read_CalcResult_struct(erpc::Codec * codec, CalcResult * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->read(data->result);

    codec->read(data->status);
}

// Read struct StringResult function implementation
static void read_StringResult_struct(erpc::Codec * codec, StringResult * data)
{
    if(NULL == data)
    {
        return;
    }

    {
        uint32_t output_str_len;
        char * output_str_local;
        codec->readString(output_str_len, &output_str_local);
        data->output_str = (char*) erpc_malloc((output_str_len + 1) * sizeof(char));
        if ((data->output_str == NULL) || (output_str_local == NULL))
        {
            codec->updateStatus(kErpcStatus_MemoryError);
        }
        else
        {
            memcpy(data->output_str, output_str_local, output_str_len);
            (data->output_str)[output_str_len] = 0;
        }
    }

    codec->read(data->count);

    codec->read(data->status);
}

// Read struct IntArray function implementation
static void read_IntArray_struct(erpc::Codec * codec, IntArray * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->read(data->length);

    read_list_int32_1_t_struct(codec, &(data->data));
}

// Read struct list_int32_1_t function implementation
static void read_list_int32_1_t_struct(erpc::Codec * codec, list_int32_1_t * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->startReadList(data->elementsCount);
    data->elements = (int32_t *) erpc_malloc(data->elementsCount * sizeof(int32_t));
    if ((data->elements == NULL) && (data->elementsCount > 0))
    {
        codec->updateStatus(kErpcStatus_MemoryError);
    }
    for (uint32_t listCount = 0U; listCount < data->elementsCount; ++listCount)
    {
        codec->read(data->elements[listCount]);
    }
}




DemoService_client::DemoService_client(ClientManager *manager)
:m_clientManager(manager)
{
}

DemoService_client::~DemoService_client()
{
}

// DemoService interface calculate function client shim.
CalcResult * DemoService_client::calculate(int32_t a, int32_t b, ArithmeticOp operation)
{
    erpc_status_t err = kErpcStatus_Success;

    CalcResult * result = NULL;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_calculateId, request.getSequence());

        codec->write(a);

        codec->write(b);

        codec->write(static_cast<int32_t>(operation));

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        result = (CalcResult *) erpc_malloc(sizeof(CalcResult));
        if (result == NULL)
        {
            codec->updateStatus(kErpcStatus_MemoryError);
        }
        read_CalcResult_struct(codec, result);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_calculateId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    return result;
}

// DemoService interface processString function client shim.
StringResult * DemoService_client::processString(const char * input, StringOp operation)
{
    erpc_status_t err = kErpcStatus_Success;

    StringResult * result = NULL;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_processStringId, request.getSequence());

        {
            uint32_t input_len = strlen((const char*)input);

            erpc_assert(64 >= 0);
            erpc_assert(input_len <= static_cast<uint32_t>(64));

            codec->writeString(input_len, (const char*)input);
        }

        codec->write(static_cast<int32_t>(operation));

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        result = (StringResult *) erpc_malloc(sizeof(StringResult));
        if (result == NULL)
        {
            codec->updateStatus(kErpcStatus_MemoryError);
        }
        read_StringResult_struct(codec, result);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_processStringId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    return result;
}

// DemoService interface sortArray function client shim.
IntArray * DemoService_client::sortArray(const IntArray * input_array)
{
    erpc_status_t err = kErpcStatus_Success;

    IntArray * result = NULL;

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb preCB = m_clientManager->getPreCB();
    if (preCB)
    {
        preCB();
    }
#endif

    // Get a new request.
    RequestContext request = m_clientManager->createRequest(false);

    // Encode the request.
    Codec * codec = request.getCodec();

    if (codec == NULL)
    {
        err = kErpcStatus_MemoryError;
    }
    else
    {
        codec->startWriteMessage(message_type_t::kInvocationMessage, m_serviceId, m_sortArrayId, request.getSequence());

        write_IntArray_struct(codec, input_array);

        // Send message to server
        // Codec status is checked inside this function.
        m_clientManager->performRequest(request);

        result = (IntArray *) erpc_malloc(sizeof(IntArray));
        if (result == NULL)
        {
            codec->updateStatus(kErpcStatus_MemoryError);
        }
        read_IntArray_struct(codec, result);

        err = codec->getStatus();
    }

    // Dispose of the request.
    m_clientManager->releaseRequest(request);

    // Invoke error handler callback function
    m_clientManager->callErrorHandler(err, m_sortArrayId);

#if ERPC_PRE_POST_ACTION
    pre_post_action_cb postCB = m_clientManager->getPostCB();
    if (postCB)
    {
        postCB();
    }
#endif


    return result;
}
