/*
 * Enhanced RPC Demo Service for Bachelor Thesis
 * "Implementation and Evaluation of a Lightweight RPC System 
 * for Resource-Constrained Devices using RIOT OS"
 * 
 * Demonstrates various data types: integers, enums, strings, arrays, structs
 */

/*
 * Generated by erpcgen 1.14.0 on Mon Dec  8 10:24:32 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "demo_service_server.hpp"
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
#include <new>
#include "erpc_port.h"
#endif
#include "erpc_manually_constructed.hpp"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

using namespace erpc;
using namespace std;
using namespace erpcShim;

#if ERPC_NESTED_CALLS_DETECTION
extern bool nestingDetection;
#endif


//! @brief Function to read struct IntArray
static void read_IntArray_struct(erpc::Codec * codec, IntArray * data);

//! @brief Function to read struct list_int32_1_t
static void read_list_int32_1_t_struct(erpc::Codec * codec, list_int32_1_t * data);


// Read struct IntArray function implementation
static void read_IntArray_struct(erpc::Codec * codec, IntArray * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->read(data->length);

    read_list_int32_1_t_struct(codec, &(data->data));
}

// Read struct list_int32_1_t function implementation
static void read_list_int32_1_t_struct(erpc::Codec * codec, list_int32_1_t * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->startReadList(data->elementsCount);
    data->elements = (int32_t *) erpc_malloc(data->elementsCount * sizeof(int32_t));
    if ((data->elements == NULL) && (data->elementsCount > 0))
    {
        codec->updateStatus(kErpcStatus_MemoryError);
    }
    for (uint32_t listCount = 0U; listCount < data->elementsCount; ++listCount)
    {
        codec->read(data->elements[listCount]);
    }
}


//! @brief Function to write struct CalcResult
static void write_CalcResult_struct(erpc::Codec * codec, const CalcResult * data);

//! @brief Function to write struct StringResult
static void write_StringResult_struct(erpc::Codec * codec, const StringResult * data);

//! @brief Function to write struct IntArray
static void write_IntArray_struct(erpc::Codec * codec, const IntArray * data);

//! @brief Function to write struct list_int32_1_t
static void write_list_int32_1_t_struct(erpc::Codec * codec, const list_int32_1_t * data);


// Write struct CalcResult function implementation
static void write_CalcResult_struct(erpc::Codec * codec, const CalcResult * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->write(data->result);

    codec->write(data->status);
}

// Write struct StringResult function implementation
static void write_StringResult_struct(erpc::Codec * codec, const StringResult * data)
{
    if(NULL == data)
    {
        return;
    }

    {
        uint32_t output_str_len = strlen((const char*)data->output_str);

        codec->writeString(output_str_len, (const char*)data->output_str);
    }

    codec->write(data->count);

    codec->write(data->status);
}

// Write struct IntArray function implementation
static void write_IntArray_struct(erpc::Codec * codec, const IntArray * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->write(data->length);

    write_list_int32_1_t_struct(codec, &(data->data));
}

// Write struct list_int32_1_t function implementation
static void write_list_int32_1_t_struct(erpc::Codec * codec, const list_int32_1_t * data)
{
    if(NULL == data)
    {
        return;
    }

    codec->startWriteList(data->elementsCount);
    for (uint32_t listCount = 0U; listCount < data->elementsCount; ++listCount)
    {
        codec->write(data->elements[listCount]);
    }
}


//! @brief Function to free space allocated inside struct StringResult
static void free_StringResult_struct(StringResult * data);

//! @brief Function to free space allocated inside struct IntArray
static void free_IntArray_struct(IntArray * data);

//! @brief Function to free space allocated inside struct list_int32_1_t
static void free_list_int32_1_t_struct(list_int32_1_t * data);


// Free space allocated inside struct StringResult function implementation
static void free_StringResult_struct(StringResult * data)
{
    erpc_free(data->output_str);
}

// Free space allocated inside struct IntArray function implementation
static void free_IntArray_struct(IntArray * data)
{
    free_list_int32_1_t_struct(&data->data);
}

// Free space allocated inside struct list_int32_1_t function implementation
static void free_list_int32_1_t_struct(list_int32_1_t * data)
{
    erpc_free(data->elements);
}



DemoService_service::DemoService_service(DemoService_interface *_DemoService_interface)
    : erpc::Service(DemoService_interface::m_serviceId)
    , m_handler(_DemoService_interface)
{
}

DemoService_service::~DemoService_service()
{
}

// return service interface handler.
DemoService_interface* DemoService_service::getHandler(void)
{
    return m_handler;
}

// Call the correct server shim based on method unique ID.
erpc_status_t DemoService_service::handleInvocation(uint32_t methodId, uint32_t sequence, Codec * codec, MessageBufferFactory *messageFactory, Transport * transport)
{
    erpc_status_t erpcStatus;
    switch (methodId)
    {
        case DemoService_interface::m_calculateId:
        {
            erpcStatus = calculate_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case DemoService_interface::m_processStringId:
        {
            erpcStatus = processString_shim(codec, messageFactory, transport, sequence);
            break;
        }

        case DemoService_interface::m_sortArrayId:
        {
            erpcStatus = sortArray_shim(codec, messageFactory, transport, sequence);
            break;
        }

        default:
        {
            erpcStatus = kErpcStatus_InvalidArgument;
            break;
        }
    }

    return erpcStatus;
}

// Server shim for calculate of DemoService interface.
erpc_status_t DemoService_service::calculate_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    int32_t a;
    int32_t b;
    ArithmeticOp operation;
    int32_t _tmp_local_i32;
    CalcResult * result = NULL;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(a);

    codec->read(b);

    codec->read(_tmp_local_i32);
    operation = static_cast<ArithmeticOp>(_tmp_local_i32);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->calculate(a, b, operation);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, DemoService_interface::m_serviceId, DemoService_interface::m_calculateId, sequence);

        write_CalcResult_struct(codec, result);

        err = codec->getStatus();
    }

    erpc_free(result);

    return err;
}

// Server shim for processString of DemoService interface.
erpc_status_t DemoService_service::processString_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    char * input = NULL;
    StringOp operation;
    int32_t _tmp_local_i32;
    StringResult * result = NULL;

    // startReadMessage() was already called before this shim was invoked.

    {
        uint32_t input_len;
        char * input_local;
        codec->readString(input_len, &input_local);
        if ((64 >= 0) && (input_len <= static_cast<uint32_t>(64)))
        {
            input = (char*) erpc_malloc((64 + 1) * sizeof(char));
            if ((input == NULL) || (input_local == NULL))
            {
                codec->updateStatus(kErpcStatus_MemoryError);
            }
            else
            {
                memcpy(input, input_local, input_len);
                (input)[input_len] = 0;
            }
        }
        else
        {
            codec->updateStatus(kErpcStatus_InvalidArgument);
        }
    }

    codec->read(_tmp_local_i32);
    operation = static_cast<StringOp>(_tmp_local_i32);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->processString(input, operation);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, DemoService_interface::m_serviceId, DemoService_interface::m_processStringId, sequence);

        write_StringResult_struct(codec, result);

        err = codec->getStatus();
    }

    erpc_free(input);

    if (result)
    {
        free_StringResult_struct(result);
    }
    erpc_free(result);

    return err;
}

// Server shim for sortArray of DemoService interface.
erpc_status_t DemoService_service::sortArray_shim(Codec * codec, MessageBufferFactory *messageFactory, Transport * transport, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    IntArray *input_array = NULL;
    input_array = (IntArray *) erpc_malloc(sizeof(IntArray));
    if (input_array == NULL)
    {
        codec->updateStatus(kErpcStatus_MemoryError);
    }
    IntArray * result = NULL;

    // startReadMessage() was already called before this shim was invoked.

    read_IntArray_struct(codec, input_array);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        result = m_handler->sortArray(input_array);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBufferRef(), transport->reserveHeaderSize());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset(transport->reserveHeaderSize());

        // Build response message.
        codec->startWriteMessage(message_type_t::kReplyMessage, DemoService_interface::m_serviceId, DemoService_interface::m_sortArrayId, sequence);

        write_IntArray_struct(codec, result);

        err = codec->getStatus();
    }

    if (input_array)
    {
        free_IntArray_struct(input_array);
    }
    erpc_free(input_array);

    if (result)
    {
        free_IntArray_struct(result);
    }
    erpc_free(result);

    return err;
}
