/*
 * Enhanced RPC Demo Service for Bachelor Thesis
 * "Implementation and Evaluation of a Lightweight RPC System 
 * for Resource-Constrained Devices using RIOT OS"
 * 
 * Demonstrates various data types: integers, enums, strings, arrays, structs
 */

/*
 * Generated by erpcgen 1.14.0 on Mon Dec  8 10:24:32 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "demo_service_interface.hpp"

#if 11400 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


using namespace std;
using namespace erpcShim;

DemoService_interface::~DemoService_interface(void)
{
}
