/*
 * Calculator service demonstrating remote procedure calls
 */

/*
 * Generated by erpcgen 1.14.0 on Thu Oct 30 12:45:04 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_calculator_interface_hpp_)
#define _calculator_interface_hpp_

#include "calculator_common.hpp"

namespace erpcShim
{


// Abstract base class for Calculator
class Calculator_interface
{
    public:
        static const uint8_t m_serviceId = 1;
        static const uint8_t m_addId = 1;
        static const uint8_t m_subtractId = 2;
        static const uint8_t m_multiplyId = 3;
        static const uint8_t m_divideId = 4;

        virtual ~Calculator_interface(void);

        virtual int32_t add(int32_t a, int32_t b) = 0;

        virtual int32_t subtract(int32_t a, int32_t b) = 0;

        virtual int32_t multiply(int32_t a, int32_t b) = 0;

        virtual float divide(int32_t a, int32_t b) = 0;
private:
};
} // erpcShim


#endif // _calculator_interface_hpp_
