/*
 * Simple multiply service demo
 */

/*
 * Generated by erpcgen 1.14.0 on Fri Oct 17 16:27:45 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_multiply_demo_server_h_)
#define _c_multiply_demo_server_h_

#include "multiply_demo_common.h"

#if defined(__cplusplus)
extern "C"
{
#endif

typedef void * erpc_service_t;

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief MultiplyService identifiers */
enum _MultiplyService_ids
{
    kMultiplyService_service_id = 1,
    kMultiplyService_multiply_id = 1,
};

//! @name MultiplyService
//@{
int32_t multiply(int32_t a, int32_t b);
//@}


#endif // ERPC_FUNCTIONS_DEFINITIONS

/*! @brief Return MultiplyService_service service object. */
erpc_service_t create_MultiplyService_service(void);

/*! @brief Destroy MultiplyService_service service object. */
void destroy_MultiplyService_service(erpc_service_t service);


#if defined(__cplusplus)
}
#endif

#endif // _c_multiply_demo_server_h_
