/*
 * Simple multiply service demo
 */

/*
 * Generated by erpcgen 1.14.0 on Fri Oct 17 16:27:45 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_multiply_demo_client_hpp_)
#define _multiply_demo_client_hpp_

#include "multiply_demo_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class MultiplyService_client: public MultiplyService_interface
{
    public:
        MultiplyService_client(erpc::ClientManager *manager);

        virtual ~MultiplyService_client();

        virtual int32_t multiply(int32_t a, int32_t b);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _multiply_demo_client_hpp_
