/*
 * Simple multiply service demo
 */

/*
 * Generated by erpcgen 1.14.0 on Fri Oct 17 16:27:45 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_multiply_demo_interface_hpp_)
#define _multiply_demo_interface_hpp_

#include "multiply_demo_common.hpp"

namespace erpcShim
{


// Abstract base class for MultiplyService
class MultiplyService_interface
{
    public:
        static const uint8_t m_serviceId = 1;
        static const uint8_t m_multiplyId = 1;

        virtual ~MultiplyService_interface(void);

        virtual int32_t multiply(int32_t a, int32_t b) = 0;
private:
};
} // erpcShim


#endif // _multiply_demo_interface_hpp_
